### ISSUE TITLE
Tesselating block in world error

### ISSUE THREAD

**Issue by skellitor301** [TimStewartJ/TheMightyArchitectury#16]
I am running a server and added this recently. I got an error from one of my members stating his game started to crash soon after I added this and they sent me the error and logs:

```
[01:58:56] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Tesselating block in world
	at net.minecraft.class_776.method_3355(class_776.java:68) ~[client-intermediary.jar:?]
	at com.timmie.mightyarchitect.control.SchematicRenderer.lambda$redraw$0(SchematicRenderer.java:113) ~[mightyarchitect-0.9.0-FABRIC.jar:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at com.timmie.mightyarchitect.control.SchematicRenderer.redraw(SchematicRenderer.java:93) ~[mightyarchitect-0.9.0-FABRIC.jar:?]
	at com.timmie.mightyarchitect.control.SchematicRenderer.tick(SchematicRenderer.java:60) ~[mightyarchitect-0.9.0-FABRIC.jar:?]
	at com.timmie.mightyarchitect.MightyClient.onTick(MightyClient.java:53) ~[mightyarchitect-0.9.0-FABRIC.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-9.1.12-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-9.1.12-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar:?]
	at jdk.proxy2.$Proxy212.tick(Unknown Source) ~[?:?]
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$3(EventHandlerImpl.java:55) ~[architectury-9.1.12-fabric.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-3792d0d4b63e847b.jar:?]
	at net.minecraft.class_310.handler$dhg000$fabric-lifecycle-events-v1$onEndTick(class_310.java:16022) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1957) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.25.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.25.jar:?]
Caused by: java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.putInt(Unknown Source) ~[?:?]
	at net.minecraft.class_287.putInt(class_287.java:3313) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.handler$ehg000$iris$beforeNext(class_287.java:3221) ~[client-intermediary.jar:?]
	at net.minecraft.class_287.method_1344(class_287.java) ~[client-intermediary.jar:?]
	at link.infra.indium.renderer.render.AbstractRenderContext.bufferQuad(AbstractRenderContext.java:134) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.bufferQuad(NonTerrainBlockRenderContext.java:50) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:129) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:74) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[indium-1.0.27+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:601) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:66) ~[indium-1.0.27+mc1.20.1.jar:?]
	at net.minecraft.class_778.handler$ebl000$indium$hookRender(class_778.java:1553) ~[client-intermediary.jar:?]
	at net.minecraft.class_778.method_3374(class_778.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_776.method_3355(class_776.java:60) ~[client-intermediary.jar:?]
	... 22 more
```
[log](https://gist.github.com/skellitor301/36d1e15778c61f8e9bca9771a556f2a0)
He couldn't get a crash log so he sent me a full log.

**Comment by TimStewartJ** [comment]
Should be fixed with latest changes
